refresh_rate: 30 seconds
appenders:
  stdout:
    kind: file
    path: "log/requests.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.6f)} {f:>15.25} {h({l}):<5.5} - {m}{n}"
root:
  level: trace
  appenders:
    - stdout
loggers:
  app:
    level: info
